version: "3.9"

services:
  payment:
    build: ./payment_service
    ports:
      - "5000:5000"

  inventory:
    build: ./inventory_service
    ports:
      - "5001:5000"

  cart:
    build: ./cart_service
    ports:
      - "5002:5000"

  orchestrator:
    build: ./orchestrator_service
    ports:
      - "5003:5000"
